version: '3.8'

services:
  # Adminer - Web-based database management
  adminer:
    image: adminer:4.8.1
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DESIGN=nette
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped